const products=[
  {id:1,name:'Polerón Field Classic',type:'Hombre · verde oscuro',price:68,tag:'NUEVO',image:'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=900&q=85'},
  {id:2,name:'Gorro Gold Line',type:'Accesorio · dorado',price:29,tag:'FAVORITO',image:'https://images.unsplash.com/photo-1521369909029-2afed882baee?auto=format&fit=crop&w=900&q=85'},
  {id:3,name:'Polera Game Day',type:'Unisex · verde',price:38,tag:'EDICIÓN FAN',image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85'},
  {id:4,name:'Manta Stadium Cozy',type:'Hogar · verde y oro',price:44,tag:'OFERTA',image:'https://images.unsplash.com/photo-1549465220-1a8b9238cd48?auto=format&fit=crop&w=900&q=85'},
  {id:5,name:'Botella Sideline',type:'Accesorio · 750 ml',price:26,tag:'NUEVO',image:'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=900&q=85'},
  {id:6,name:'Bolso Weekend',type:'Accesorio · lona',price:62,tag:'FAN PICK',image:'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85'},
  {id:7,name:'Jockey North Field',type:'Accesorio · ajustable',price:31,tag:'NUEVO',image:'https://images.unsplash.com/photo-1588850561407-ed78c282e89b?auto=format&fit=crop&w=900&q=85'},
  {id:8,name:'Calcetines Rally',type:'Accesorio · par',price:18,tag:'OFERTA',image:'https://images.unsplash.com/photo-1586350977771-b3b0abd50c82?auto=format&fit=crop&w=900&q=85'}
];
let cart=[];const money=n=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);const grid=document.querySelector('#productGrid'),drawer=document.querySelector('#cartDrawer'),shade=document.querySelector('#cartShade');
function renderProducts(list=products){grid.innerHTML=list.map(p=>`<article class="product"><div class="product-image"><img src="${p.image}" alt="${p.name}"><span class="tag">${p.tag}</span></div><div class="product-info"><small>${p.type}</small><h3>${p.name}</h3><div class="price-row"><b>${money(p.price)}</b><button class="add-button" data-add="${p.id}" aria-label="Agregar ${p.name}">+</button></div></div></article>`).join('')}
function renderCart(){document.querySelector('#cartCount').textContent=cart.length;document.querySelector('#cartItems').innerHTML=cart.length?cart.map(p=>`<div class="cart-row"><img src="${p.image}" alt=""><span>${p.name}<b>${money(p.price)}</b></span><button data-remove="${p.id}" class="text-button">Quitar</button></div>`).join(''):'<p>Tu bolsa está vacía.</p>';document.querySelector('#cartTotal').textContent=money(cart.reduce((total,p)=>total+p.price,0))}
function openCart(open=true){drawer.classList.toggle('open',open);shade.classList.toggle('show',open);drawer.setAttribute('aria-hidden',String(!open))}grid.addEventListener('click',e=>{const id=Number(e.target.dataset.add);if(!id)return;cart.push(products.find(p=>p.id===id));renderCart();openCart()});drawer.addEventListener('click',e=>{const id=Number(e.target.dataset.remove);if(!id)return;cart=cart.filter(p=>p.id!==id);renderCart()});document.querySelector('#cartButton').addEventListener('click',()=>openCart());document.querySelector('#closeCart').addEventListener('click',()=>openCart(false));shade.addEventListener('click',()=>openCart(false));document.querySelector('#menuButton').addEventListener('click',e=>{const nav=document.querySelector('#mainNav'),open=nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',String(open))});document.querySelector('#filterButton').addEventListener('click',e=>{const on=e.currentTarget.textContent==='Ver todo';renderProducts(on?products.filter(p=>p.tag==='OFERTA'):products);e.currentTarget.textContent=on?'Ver ofertas':'Ver todo'});renderProducts();renderCart();
